language: java
dist: trusty
sudo: required
jdk:
- oraclejdk8
services:
- postgresql
addons:
  postgresql: "10.5"
apt:
  packages:
  - postgresql-10
  - postgresql-client-10
env:
  global:
  - PGPORT=5433
test:
    adapter: postgresql
    database: travis_ci_test
    username: igor
    password: flash00