language: java
dist: trusty
sudo: required
jdk:
- oraclejdk8
services:
- postgresql
addons:
  postgresql: "10.5"
#  sonarcloud:
#    organization: "l1maigor-github"
#    token:
#      secure: "${SONAR_TOKEN}"
cache:
  directories:
  - $HOME/.m2
before_script:
- psql -c "CREATE DATABASE hospitalVeterinario;" -U postgres
- psql -c "CREATE USER igor WITH PASSWORD 'flash00';" -U postgres
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
#deploy:
#  provider: heroku
#  api_key:
#    secure: "${HEROKU_TOKEN}"
#  app: hospital-veterinario-api